routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('master');
});
Route::resource('post', 'PostController');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $guarded = [];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PostRequest;
use App\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::all();
        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('posts.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostRequest $request)
    {
        try {
            Post::create([
                'title' => $request->title,
                'body' => $request->body,
            ]);
            return redirect()->route('post.index')->with(['success' => 'Post created successfully']);

        } catch (Exception $e) {
            return back()->withErrors(['message' => 'Something went wrong']);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('posts.show', compact('post'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        return view('posts.edit', compact('post'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(PostRequest $request, Post $post)
    {
        try {
            $post->title = $request->title;
            $post->body = $request->body;
            $post->save();
            return redirect()->route('post.index')->with(['success' => 'Post updated successfully']);

        } catch (Exception $e) {
            return back()->withErrors(['message' => 'Something went wrong']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();
        return redirect()->route('post.index')->with(['success' => 'Post deleted successfully']);

    }
}

resources/views/master.blade.php
@include('partials.header')
@include('partials.nav')
<div class="container">
@if(count($errors) > 0)
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <ul>
        @foreach($errors->all() as $error)
            <li>{{$error}}</li>
        @endforeach
      </ul>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
@endif
@if(Session::has('success'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      {{Session::get('success')}}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
@endif
  <div class="row">
    <div class="col-2">

    </div>
    <div class="col-8">
      @yield('content')
    </div>
    <div class="col-2">

    </div>
  </div>
</div>

@include('partials.footer')

resources/views/partials/footer.blade.php
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

resources/views/partials/header.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>

resources/views/partials/nav.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/post">Crud App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/post">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/post">Posts</a>
      </li>

    </ul>

  </div>
</nav>

resources/views/posts/create.blade.php
@extends('master')
@section('content')

<form action="{{route('post.store')}}" method="post">
@csrf
  <div class="form-group">
    <label for="TitleInput">Title</label>
    <input type="title" class="form-control" id="TitleInput" aria-describedby="titlehelp" placeholder="Title" name="title" required size="32">
  </div>
  <div class="form-group">
    <label for="BodyInput">Body</label>
    <textarea class="form-control" id="BodyInput" placeholder="Body" rows="5" name="body" maxlength="65535" required></textarea>
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>


@endsection

resources/views/posts/edit.blade.php
@extends('master')
@section('content')

<form action="{{url('/post/' . $post->id)}}" method="post">
@method('PUT')
@csrf
  <div class="form-group">
    <label for="TitleInput">Title</label>
    <input type="title" class="form-control" id="TitleInput" aria-describedby="titlehelp" placeholder="Title" name="title" value="{{$post->title}}" required size="32">
  </div>
  <div class="form-group">
    <label for="BodyInput">Body</label>
    <textarea class="form-control" id="BodyInput" placeholder="Body" rows="5" name="body" maxlength="65535" required>{{$post->body}}</textarea>
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>


@endsection

resources/views/posts/index.blade.php
@extends('master')
@section('content')

<a class="btn btn-outline-success" href="{{route('post.create')}}">create</a>
<table class="table mt-2">
  <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Body</th>
        <th scope="col">Created</th>
        <th scope="col">Updated</th>
        <th scope="col">Action</th>
        <th scope="col">Show</th>
        <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    @foreach($posts as $post)
        <tr>
            <td>{{$post->id}}</td>
            <td>{{$post->title}}</td>
            <td>{{$post->body}}</td>
            <td>{{$post->created_at}}</td>
            <td>{{$post->updated_at}}</td>
            <td><a class="btn btn-outline-primary" href="{{url('/post/'.$post->id .'/edit')}}">Edit</a></td>
            <td><a class="btn btn-outline-info" href="{{url('/post/'.$post->id )}}">Show</a></td>
            <td>
                <form action="{{url('/post/'.$post->id )}}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-outline-danger" >Delete</button>
                </form>
            </td>
        </tr>
    @endforeach
  </tbody>
</table>
@endsection

resources/views/posts/show.blade.php
@extends('master')
@section('content')

<form >
@csrf
  <div class="form-group">
    <label for="TitleInput">Title</label>
    <input type="title" class="form-control" id="TitleInput" aria-describedby="titlehelp" placeholder="Title" name="title" value="{{$post->title}}" readonly size="32">
  </div>
  <div class="form-group">
    <label for="BodyInput">Body</label>
    <textarea class="form-control" id="BodyInput" placeholder="Body" rows="5" name="body" maxlength="65535" readonly>{{$post->body}}</textarea>
  </div>
</form>


@endsection